apiVersion: v1
kind: Secret
metadata:
  name: mongo-sec
  namespace: workshop
type: Opaque
stringData:
  MONGO_URI: "mongodb://adminUser:StrongP@ssw0rd@mongodb-svc.workshop.svc.cluster.local:27017/mydatabase?authSource=admin"
